version: "3"
services:
  incredible-citizen-bot:
    build: .
    restart: always
    env_file:
      - ./.env
    command: python3 src/run.py
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - "5432"
